export default [
  {
      id: 1,
      firstname: "First",
      lastname: "Last",
      faculty: "com",
      major: "software development",
      career: "full stack",
      company: "Tech Corp",
      internshipPosition: "Frontend Developer",
      internshipCompany: "Web Solutions",
      internshipDuration: "3 months",
      internshipTasks: "Developed UI components",
      internshipFeedback: "Great learning experience",
      careerPosition: "Full Stack Developer",
      careerCompany: "Tech Corp",
      careerDate: "2024",
      careerTasks: "Building web applications",
      careerFeedback: "Challenging but rewarding",
      activities: "Coding Club",
      academicProject: "Online Voting System",
      profileImage: "https://i.pinimg.com/736x/fe/5b/83/fe5b83e7dff29a16e9ab387d4a927ea6.jpg"
  },
  {
      id: 2,
      firstname: "Jane",
      lastname: "Doe",
      faculty: "sci",
      major: "data science",
      career: "data analyst",
      company: "Data Inc",
      internshipPosition: "Data Intern",
      internshipCompany: "Insight Solutions",
      internshipDuration: "4 months",
      internshipTasks: "Analyzed datasets",
      internshipFeedback: "Improved analytical skills",
      careerPosition: "Data Analyst",
      careerCompany: "Data Inc",
      careerDate: "2023",
      careerTasks: "Interpreting data trends",
      careerFeedback: "Insightful and educational",
      activities: "Math Club",
      academicProject: "Stock Price Prediction",
      profileImage: "https://i.pinimg.com/736x/17/8b/1b/178b1b7bd863091af857e03642297234.jpg"
  },
  {
      id: 3,
      firstname: "John",
      lastname: "Smith",
      faculty: "eng",
      major: "mechanical engineering",
      career: "engineer",
      company: "AutoWorks",
      internshipPosition: "Engineering Intern",
      internshipCompany: "Auto Solutions",
      internshipDuration: "6 months",
      internshipTasks: "Designed machine parts",
      internshipFeedback: "Hands-on experience",
      careerPosition: "Mechanical Engineer",
      careerCompany: "AutoWorks",
      careerDate: "2022",
      careerTasks: "Developed engine models",
      careerFeedback: "Practical and engaging",
      activities: "Robotics Team",
      academicProject: "Electric Vehicle Prototype",
      profileImage: ""
  },
  {
      id: 4,
      firstname: "First",
      lastname: "Last",
      faculty: "com",
      major: "software development",
      career: "full stack",
      company: "Tech Corp",
      internshipPosition: "Frontend Developer",
      internshipCompany: "Web Solutions",
      internshipDuration: "3 months",
      internshipTasks: "Developed UI components",
      internshipFeedback: "Great learning experience",
      careerPosition: "Full Stack Developer",
      careerCompany: "Tech Corp",
      careerDate: "2024",
      careerTasks: "Building web applications",
      careerFeedback: "Challenging but rewarding",
      activities: "Coding Club",
      academicProject: "Online Voting System",
      profileImage: ""
  },
  {
      id: 5,
      firstname: "Jane",
      lastname: "Doe",
      faculty: "sci",
      major: "data science",
      career: "data analyst",
      company: "Data Inc",
      internshipPosition: "Data Intern",
      internshipCompany: "Insight Solutions",
      internshipDuration: "4 months",
      internshipTasks: "Analyzed datasets",
      internshipFeedback: "Improved analytical skills",
      careerPosition: "Data Analyst",
      careerCompany: "Data Inc",
      careerDate: "2023",
      careerTasks: "Interpreting data trends",
      careerFeedback: "Insightful and educational",
      activities: "Math Club",
      academicProject: "Stock Price Prediction",
      profileImage: ""
  },
  {
      id: 6,
      firstname: "John",
      lastname: "Smith",
      faculty: "eng",
      major: "mechanical engineering",
      career: "engineer",
      company: "AutoWorks",
      internshipPosition: "Engineering Intern",
      internshipCompany: "Auto Solutions",
      internshipDuration: "6 months",
      internshipTasks: "Designed machine parts",
      internshipFeedback: "Hands-on experience",
      careerPosition: "Mechanical Engineer",
      careerCompany: "AutoWorks",
      careerDate: "2022",
      careerTasks: "Developed engine models",
      careerFeedback: "Practical and engaging",
      activities: "Robotics Team",
      academicProject: "Electric Vehicle Prototype",
      profileImage: ""
  }
];
